version: "3"
services:
  app-1:
    build: ./flask-app
    environment:
      - SERVER_NAME=app-1
  app-2:
    build: ./flask-app
    environment:
      - SERVER_NAME=app-2
  load-balancer:
    build: ./nginx
    ports:
      - "8080:8080"
