version: "3"
services:
  app-1:
    image: flask-app
    environment:
      - SERVER_NAME=app-1
  app-2:
    image: flask-app
    environment:
      - SERVER_NAME=app-2
  load-balancer:
    image: nginx-app
    ports:
      - "8080:8080"
