version: "3"
services:
  server:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgresql
      - redis
    environment:
      - POSTGRES_URL=postgresql:5432/dev
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
  postgresql:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379